baseURL = "https://genuine-sunflower-7b4279.netlify.app"
title = "Made to Last"
theme = "PaperMod"
paginate = 10

[params]
  description = "Project guides for construction, woodworking, and vehicles"
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowToc = true

[taxonomies]
  category = "categories"
  tag = "tags"