baseURL = "https://genuine-sunflower-7b4279.netlify.app"
title = "The Build Manual"
theme = "PaperMod"
paginate = 10

[params]
  description = "Detailed project guides for construction, woodworking, vehicles, and more"
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowToc = true

[taxonomies]
  category = "categories"
  tag = "tags"